name: Run API Tests with Postman and Newman

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00
  workflow_dispatch:  # Enable manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  # Replace with the version of Node.js you need

    - name: Install Newman and Newman HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection
      run: newman run serverest-tech-sharing.postman_collection.json -e serverest-tech-sharing.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export report.html
      continue-on-error: true

    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: HTML Report
        path: report.html

    - name: Publish HTML Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        commit_message: Update the test report
    
    - name: Display Test Report URL
      run: |
        echo "Test report: https://${{ github.actor }}.github.io/serverest-tech-sharing/report.html"