name: Run API Tests with Postman and Newman  # Name of the workflow

on:
  push:
    branches:
      - master  # Trigger the workflow when a commit is pushed to the master branch
  schedule:
    - cron: '0 0 * * *'  # Trigger the workflow every day at midnight
  workflow_dispatch:   # Trigger the workflow manually from the Actions tab

jobs:
  setup-and-run-tests: # Stage name
    name: Setup the environment and run the tests
    runs-on: ubuntu-latest  # Run the job on the latest version of Ubuntu

    steps:
      # Check out the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install Newman and Newman HTML Reporter globally
      - name: Install Newman and Newman HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run Postman Collection using Newman and export an HTML report
      - name: Run Postman Collection
        run: newman run serverest-tech-sharing.postman_collection.json -e serverest-tech-sharing.postman_environment.json --reporters cli,htmlextra,json --reporter-htmlextra-export report.html --reporter-json-export report.json
        continue-on-error: true   # Continue even if there are errors in the tests

      # Read the JSON report to get tests data
      - name: Read report.json and set test results into env variables
        run: |
          totalRequests=$(jq -r '.run.stats.requests.total' report.json)
          totalTests=$(jq -r '.run.stats.assertions.total' report.json)
          failedTests=$(jq -r '.run.stats.assertions.failed' report.json)
          passedTests=$(expr $totalTests - $failedTests)
          echo "TOTAL_REQUESTS=$totalRequests" >> $GITHUB_ENV
          echo "TOTAL_TESTS=$totalTests" >> $GITHUB_ENV
          echo "FAILED_TESTS=$failedTests" >> $GITHUB_ENV
          echo "PASSED_TESTS=$passedTests" >> $GITHUB_ENV

      # Upload the HTML report as an artifact
      - name: Publish HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: HTML Report
          path: report.html

      # Publish the HTML report to GitHub Pages
      - name: Publish HTML Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          commit_message: Update the test report

      # Display the URL of the published HTML report to the console
      - name: Display Test Report URL
        run: |
          echo "Test report: https://${{ github.actor }}.github.io/serverest-tech-sharing/report.html"
      
      - name: Send Slack Notification with Test Results
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "channel": "'"${SLACK_CHANNEL}"'",
            "attachments": [
              {
                "title": "Postman + Newman Tests",
                "text": ":page_with_curl: *Total Requests:* ${{ env.TOTAL_REQUESTS }}\n:page_facing_up: *Total Tests:* ${{ env.TOTAL_TESTS }}\n:white_check_mark: *Passed Tests:* ${{ env.PASSED_TESTS }}\n:x: *Failed Tests:* ${{ env.FAILED_TESTS }}\n\n<https://${{ github.actor }}.github.io/serverest-tech-sharing/report.html|Click here to see the test in details>"
              }
            ]
          }' "${SLACK_WEBHOOK_URL}"
