name: Run API Tests with Postman and Newman

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  # Replace with the version of Node.js you need

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: newman run serverest-tech-sharing.postman_collection.json -e serverest-tech-sharing.postman_environment.json