name: Run API Tests with Postman and Newman

on:
  push:
    branches:
      - master  
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch: # Enable the run worklfow button on the Action

jobs:
  setup-and-run-tests: 
    name: Setup the environment and run the tests
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Newman and Newman HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: newman run serverest-tech-sharing.postman_collection.json -e serverest-tech-sharing.postman_environment.json --reporters cli,htmlextra,json --reporter-htmlextra-export report.html --reporter-json-export report.json
        continue-on-error: true

      - name: Read report.json and set test results into env variables
        run: |
          totalRequests=$(jq -r '.run.stats.requests.total' report.json)
          totalTests=$(jq -r '.run.stats.assertions.total' report.json)
          failedTests=$(jq -r '.run.stats.assertions.failed' report.json)
          passedTests=$(expr $totalTests - $failedTests)
          echo "TOTAL_REQUESTS=$totalRequests" >> $GITHUB_ENV
          echo "TOTAL_TESTS=$totalTests" >> $GITHUB_ENV
          echo "FAILED_TESTS=$failedTests" >> $GITHUB_ENV
          echo "PASSED_TESTS=$passedTests" >> $GITHUB_ENV

      - name: Publish HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: HTML Report
          path: report.html

      - name: Publish HTML Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          commit_message: Update the test report

      - name: Display Test Report URL
        run: |
          echo "Test report: https://${{ github.actor }}.github.io/newman-serverest-demo/report.html"
      
      - name: Send Slack Notification with Test Results
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: |
          if [[ ${{ env.FAILED_TESTS }} -gt 0 ]]; then
            color="#FF0000"
          else
            color="#00FF00"
          fi

          curl -X POST -H 'Content-type: application/json' --data '{
            "channel": "'"${SLACK_CHANNEL}"'",
            "attachments": [
              {
                "title": "Test Results",
                "text": ":page_with_curl: *Total Requests:* ${{ env.TOTAL_REQUESTS }}\n:page_facing_up: *Total Tests:* ${{ env.TOTAL_TESTS }}\n:white_check_mark: *Passed Tests:* ${{ env.PASSED_TESTS }}\n:x: *Failed Tests:* ${{ env.FAILED_TESTS }}\n\n<https://${{ github.actor }}.github.io/serverest-tech-sharing/report.html|Click here to see the last test run in details>",
                "color": "'"${color}"'"
              }
            ]
          }' "${SLACK_WEBHOOK_URL}"
